name: .NET Core

on: 
  push:
    branches: 
      - TestBuild

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build ./Microsoft.Toolkit.Parsers/Microsoft.Toolkit.Parsers.csproj --configuration Release -p:VersionSuffix=6.0.0 --version-suffix test-$(date +%Y%m%d%H%M%S)
    - name: Pack
      run: dotnet pack ./Microsoft.Toolkit.Parsers/Microsoft.Toolkit.Parsers.csproj --configuration Release -p:VersionSuffix=6.0.0 --version-suffix test-$(date +%Y%m%d%H%M%S)
